[package]
name = "parrot"
version = "0.1.0"
authors = ["zxv <zxv@tfwno.gf>"]

[dependencies]
image         = "0.17"
docopt        = "*"
docopt_macros = "*"
serde         = "1.0"
serde_derive  = "1.0"
